const mongoose = require('mongoose');

const CuotaSchema = new mongoose.Schema({
  numeroCuota:      { type: Number, required: true },
  fechaVencimiento: { type: Date, required: true },
  montoCapital:     { type: Number, required: true },
  montoInteres:     { type: Number, required: true },
  montoCuota:       { type: Number, required: true },
  montoPagado:      { type: Number, default: 0 },
  montoMora:        { type: Number, default: 0 },
  estado:           { type: String, enum: ['pendiente', 'pagada', 'vencida', 'parcial'], default: 'pendiente' },
  fechaPago:        Date,
}, { _id: true });

const PrestamoSchema = new mongoose.Schema({
  empresaId: { type: mongoose.Schema.Types.ObjectId, ref: 'Empresa', required: true },
  clienteId:           { type: mongoose.Schema.Types.ObjectId, ref: 'Cliente', required: true },
  usuarioId:           { type: mongoose.Schema.Types.ObjectId, ref: 'Usuario', required: true },
  numeroPrestamo:      { type: String, required: true, unique: true },
  tipoPrestamo:        {
    type: String,
    enum: ['personal','hipotecario','vehicular','comercial','empresarial','educativo','con_garantia','sin_garantia'],
    required: true,
  },
  tipoCalculo: { type: String, enum: ['frances','simple','aleman','bullet'], default: 'frances' },
  descripcionDestino:  { type: String, required: true },
  tieneGarantia:       { type: Boolean, default: false },
  tipoGarantia:        { type: String, default: 'ninguna' },
  descripcionGarantia: String,
  valorGarantia:       Number,
  montoSolicitado:     { type: Number, required: true },
  inicial:             { type: Number, default: 0 },
  montoFinanciado:     { type: Number, required: true },
  tasaInteres:         { type: Number, required: true },
  plazoMeses:          { type: Number, required: true },
  frecuenciaPago:      { type: String, enum: ['diario','semanal','quincenal','mensual'], default: 'mensual' },
  totalCuotas:         { type: Number, required: true },
  montoCuota:          { type: Number, required: true },
  totalIntereses:      { type: Number, required: true },
  totalPagar:          { type: Number, required: true },
  fechaInicio:         { type: Date, default: Date.now },
  fechaVencimiento:    { type: Date, required: true },
  estado:              { type: String, enum: ['activo','pagado','vencido','recuperado','cancelado'], default: 'activo' },
  cuotas:              [CuotaSchema],
  saldoPendiente:      { type: Number, required: true },
  capitalPagado:       { type: Number, default: 0 },
  interesesPagados:    { type: Number, default: 0 },
  tasaMoraDiaria:      { type: Number, default: 0.5 },
  cuotasPagadas:       { type: Number, default: 0 },
  cuotasVencidas:      { type: Number, default: 0 },
  diasMora:            { type: Number, default: 0 },
  montoMoraAcumulada:  { type: Number, default: 0 },
  observaciones:       String,
}, { timestamps: true });

module.exports = mongoose.model('Prestamo', PrestamoSchema);
